config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :forum_threads do    
    resources :forum_posts, moduel: :forum_threads   
  end 

  root to: "forum_threads#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forum_post.rb
# == Schema Information
#
# Table name: forum_posts
#
#  id              :integer          not null, primary key
#  body            :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  forum_thread_id :integer
#  user_id         :integer
#

class ForumPost < ApplicationRecord
  belongs_to :user 
  belongs_to :forum_thread 
  
end

app/models/forum_thread.rb
# == Schema Information
#
# Table name: forum_threads
#
#  id         :integer          not null, primary key
#  subject    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class ForumThread < ApplicationRecord
  belongs_to :user 
  has_many :forum_posts
  accepts_nested_attributes_for :forum_posts 

  validates :subject, presence: true 
  validates_associated :forum_posts 
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :forum_threads
         has_many :forum_posts
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forum_threads_controller.rb
class ForumThreadsController<ApplicationController 
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_forum_thread, except: [:index, :new, :create]

  def index 
    @forum_threads = ForumThread.all 
  end 

  def show 
  end 

  def new 
    @forum_thread = ForumThread.new 
    @forum_thread.forum_posts.new 
  end 

  def create 
    @forum_thread = current_user.forum_threads.new(forum_thread_params)
    @forum_thread.forum_posts.first.user_id = current_user.id 

    if @forum_thread.save 
      redirect_to @forum_thread 
    else
      render :new  
    end 
  end 

  private 

  def set_forum_thread
    @forum_thread = ForumThread.find(params[:id])
  end 

  def forum_thread_params 
    params.require(:forum_thread).permit(:subject, forum_posts_attributes: [:body])
  end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/forum_posts/_forum_post.html.erb
  <p class="text-muted">Posted by <%= forum_post.user.first_name %> <%= local_time_ago forum_post.created_at %></p>
  <p><%= markdownify forum_post.body %></p>

app/views/forum_threads/_form.html.erb
<%= form_for(@forum_thread) do |f| %>

  <div class="form-group">
    <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
  </div>

    <%= f.fields_for :forum_posts do |p| %>
      <div class="form-group">
        <%= p.text_area :body, placeholder: "Add Comment", rows: 10, class: "form-control" %>
      </div>
    <% end %>

  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/forum_threads/_forum_thread.html.erb
<%= link_to forum_thread do %>
  <h3><%= forum_thread.subject %></h3>
<% end %>

app/views/forum_threads/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/forum_threads/show.html.erb
<div class="container">
  <h1><%= @forum_thread.subject %></h1>
  <p class="text-muted">Created by <%= @forum_thread.user.email %></p>
  
  <hr />

  <% @forum_thread.forum_posts.each do |forum_post| %>
    <p class="text-muted">Posted by <%= forum_post.user.email %></p>
    <%= forum_post.body %>
  <% end %>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>ManageForum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
      <div class="container">
        <%= flash.notice %>
        <%= flash.alert %>
    <%= yield %>
    </div>

     </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Forum</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <li><%= link_to "Threads", forum_threads_path, class: "nav-link" %></li>
      </li>
      </ul>
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <% if user_signed_in? %>
            <li><%= link_to "Account", edit_user_registration_path, class: 'nav-link' %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %></li>
            <li><%= link_to "Login", new_user_session_path, class: 'nav-link' %></li>
          <% end %>
        </li>
      </ul> 
  </div>
</nav>


      

    

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>